### ISSUE TITLE
Config Question

### ISSUE THREAD

**Issue by ohlawdie** [bantya/Keypirinha-Zealous#1]
![image](https://user-images.githubusercontent.com/30779615/65706206-f5ac5800-e057-11e9-8938-01739c6cdf08.png)

Hey Bantya, I am unsure what I'm doing wrong...I've got the necessary fields populated on the right hand side for the writable config file. Thanks!

**Comment by bantya** [comment]
@evanricard, I can't understand your problem. Can you please elaborate? Please provide steps to replicate your issue. 😀

And, sorry for late reply. 😒

**Comment by ohlawdie** [comment]
No problem @bantya, looking back at this...I can't quite understand it myself sorry I should have clarified. I am trying to filter keypirinha when I want to do a search through zeal for a specific data type or object that I might need to know about at any given time for programming. Specifically, I was trying to configure your package so I basically copied the read-only version of the configuration file, uncommented the text, and then pasted into the writable config, zealous.ini. 

Unfortunately, typing in a filter like net: for the .NET framework just prompts me to refresh your package and does not resolve to Zeal like I was hoping. Anyways, thanks!

![image](https://user-images.githubusercontent.com/30779615/67111384-d1e5b900-f1a2-11e9-9f6f-906363c9b20f.png)

**Comment by bantya** [comment]
I have a solution for you.

Looks like you did everything right but went wrong in case of **Zeal Doc Name**. As per the first screenshot you attached, your `zealous.ini` file is as:

```ini
[main]
# Plugin's main configuration section
#
# * path
#   The path to the zeal executable.
path = "C:\Program Files\Zeal"
#
# * docset_path
#   The zeal docsets path.
docset_path = "C:\Users\evanricard\AppData\Local\Zeal\Zeal\docsets"
#
# * results
#   The total results count.
result = 15

[docs]
# The zeal docs list
#
# Syntax:
#   [distinct keyword] = [zeal doc name]
#
# Examples:
#   ap = apache
#   ng = nginx
net = .NET
js = Javascript
```

The culprit here in `[docs]` section in entry `net = .NET` (also in `js = Javascript`). For the `.NET Framework`, the zeal doc identifier is `net` (**NOT** `.NET`).

Now you may ask, how on earth should I decide what to use? Good question!

Here is the paragraph where **I apologize** 😖 for not being clear about what **zeal doc identifier** to use and where to find it. The documentation fell short here.

Now to find appropriate doc identifier follow mentioned steps 🐾:

1. You should go to zeal docs folder (`docset_path` in `[main]` section) i.e. `C:\Users\USERNAME\AppData\Local\Zeal\Zeal\docsets` (in your case: `C:\Users\evanricard\AppData\Local\Zeal\Zeal\docsets`). Here you will find all of your installed docsets as:

    ![image](https://user-images.githubusercontent.com/16685565/70826513-23aa6880-1e0d-11ea-8345-db2dd2eef6a4.png)

2. Open your desired docset folder (in your case: `NET_Framework.docset`)

3. Go to `Contents` folder.
Here you will find `Info.plist` file. Open this file in your code editor (or Notepad will do). You will see something like:

    ![image](https://user-images.githubusercontent.com/16685565/70827447-48074480-1e0f-11ea-9947-8558fffe34a5.png)

4. The `Info.plist` is an XML file. Look for **key** `CFBundleIdentifier`. Copy the adjacent **string** value (in your case: `net` **NOT** `.NET`).
If by chance `CFBundleIdentifier` is not present (highly unlikely!), look for `DocSetPlatformFamily` and copy it's value.

So now you can find the exact zeal docs identifier for your docset.

ℹ **NOTE:** The identifiers have to be exactly same as given in `Info.plist` file. Case **must** be same. That's why I formerly said `js = Javascript` is also a culprit. So, your `[docs]` section should be like:

```ini
[docs]
# The zeal docs list
#
# Syntax:
#   [distinct keyword] = [zeal doc name]
#
# Examples:
#   ap = apache
#   ng = nginx
net = net
js = javascript
```

Hope this lengthy late reply solved your problem! If problem persists, consult your family doctor 😁. 

🙏🏼

**Comment by bantya** [comment]
So I am considering it as **solved** and **closing** it!

@evanricard If you want any help again, please let me know here and I will **re-open** this if required!

🙏🏼
